
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockmanager
      version: blue
  template:
    metadata:
      labels:
        app: stockmanager
        version: blue
    spec:
      containers:
      - name: stockmanager
        image: <ECR_REPO>:<TAG>
        ports:
        - containerPort: 8030
