apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockmanager
      version: canary
  template:
    metadata:
      labels:
        app: stockmanager
        version: canary
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: stockmanager
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8030
