/*
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockmanager
      version: green
  template:
    metadata:
      labels:
        app: stockmanager
        version: green
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: stockmanager
          image: 493800112687.dkr.ecr.eu-north-1.amazonaws.com/shopfront:14
          ports:
            - containerPort: 8030
*/


metadata:
  name: stockmanager-green
spec:
  selector:
    matchLabels:
      app: stockmanager
      version: green
